site_name: Natrix
strict: true
repo_url: https://github.com/AlbertoCentonze/natrix
repo_name: AlbertoCentonze/natrix
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home:
    - Welcome To Natrix: index.md
    - Quick Start: quick-start.md
    - Configuration: configuration.md
    - Metadata Limitations: metadata-limitations.md
  - Rules:
    - Overview: rules/index.md
    - Memory Expansion (NTX1): rules/memory-expansion.md
    - Constant Naming Convention (NTX2): rules/constant-naming.md
    - Implicit Internal (NTX3): rules/implicit-internal.md
    - Implicit View (NTX4): rules/implicit-view.md
    - Implicit Pure (NTX5): rules/implicit-pure.md
    - Print Left (NTX6): rules/print-left.md
    - Cache Storage Variable (NTX7): rules/storage-caching.md
    - Unused Variable (NTX8): rules/unused-variable.md
    - Implicit Export (NTX9): rules/implicit-export.md
    - Unused Argument (NTX10): rules/unused-argument.md
    - Argument Naming Convention (NTX11): rules/argument-naming.md
    - Modifiers Ordering (NTX12): rules/modifiers-ordering.md
  - API Reference: api/index.md
  - Development: development/index.md
